from top.api.rest.AliexpressAffiliateLinkGenerateRequest import AliexpressAffiliateLinkGenerateRequest
from top.api.rest.AliexpressAffiliateCategoryGetRequest import AliexpressAffiliateCategoryGetRequest
from top.api.rest.AliexpressAffiliateOrderGetRequest import AliexpressAffiliateOrderGetRequest
from top.api.rest.AliexpressAffiliateProductQueryRequest import AliexpressAffiliateProductQueryRequest
from top.api.rest.AliexpressAffiliateOrderListRequest import AliexpressAffiliateOrderListRequest
